const images = {
  baricon: require('../../assets/images/bar.png'),
  empty_bag: require('../../assets/images/empty_bag.png'),
  new_message: require('../../assets/images/new_message.png'),
  old_message: require('../../assets/images/old_message.png'),
  old_order: require('../../assets/images/old_order.png'),
  procurement_icon: require('../../assets/images/procurement.png'),
  package_icon: require('../../assets/images/package.png'),
  track_icon: require('../../assets/images/track.png'),
  deliverhistory_icon: require('../../assets/images/history.png'),
  show_download: require('../../assets/images/shoe_download.jpeg'),
  delivered_image: require('../../assets/images/delivered.png'),
  debit_image: require('../../assets/images/debit.png'),
  credit_image: require('../../assets/images/topup.png'),
  warehouse_icon: require('../../assets/images/warehouse.png'),
  manageinvent_icon: require('../../assets/images/inventory.png'),
  delivery_icon: require('../../assets/images/delivery_icon.png'),
  white_logo: require('../../assets/images/logo_white.png'),
  slider1: require('../../assets/images/slider1.png'),
  slider2: require('../../assets/images/slider2.png'),
  slider3: require('../../assets/images/slider3.png'),
  slider4: require('../../assets/images/slider4.png'),
  profileicon: require('../../assets/images/profile_icon.png'),
  businessicon: require('../../assets/images/business_icon.png'),
  sliderline: require('../../assets/images/onboard_horizontal.png'),
  new_order: require('../../assets/images/new_order.png'),
  flat_logo: require('../../assets/images/renda_logo.png'),
  filter_icon: require('../../assets/images/filter_icon.png'),
  search_icon: require('../../assets/images/search.png'),
  profile_icon_grey: require('../../assets/images/profile_icon_grey.png'),
  cell_phone_grey: require('../../assets/images/cell_phone_grey.png'),
  chat_icon_grey: require('../../assets/images/chat_icon_grey.png'),
  dashed_line: require('../../assets/images/line_dashed.png'),
  progressbar_line: require('../../assets/images/Union.png'),
  unchecked: require('../../assets/images/unchecked.png'),
  checked: require('../../assets/images/checked.png'),
  arc: require('../../assets/images/arc.png'),
  stopwatch: require('../../assets/images/stop_watch.png'),
  login_bg: require('../../assets/images/Login_BG.png'),
  login_bg2: require('../../assets/images/LOGIN_BG2.png'),
};

export default images;
