const statesList = [
  {name: 'Lagos', id: 25, value: 'lagos'},
  {name: 'Abia', id: 1, value: 'abia'},
  {name: 'Adamawa', id: 2, value: 'adamawa'},
  {name: 'Akwa Ibom', id: 3, value: 'akwa ibom'},
  {name: 'Anambra', id: 4, value: 'anambra'},
  {name: 'Bauchi', id: 5, value: 'bauchi'},
  {name: 'Bayelsa', id: 6, value: 'bayelsa'},
  {name: 'Benue', id: 7, value: 'benue'},
  {name: 'Borno', id: 8, value: 'borno'},
  {name: 'Cross River', id: 9, value: 'cross river'},
  {name: 'Delta', id: 10, value: 'delta'},
  {name: 'Ebonyi', id: 11, value: 'ebonyi'},
  {name: 'Edo', id: 12, value: 'edo'},
  {name: 'Ekiti', id: 13, value: 'ekiti'},
  {name: 'Enugu', id: 14, value: 'enugu'},
  {name: 'Abuja (FCT)', id: 15, value: 'fct'},
  {name: 'Gombe', id: 16, value: 'gombe'},
  {name: 'Imo', id: 17, value: 'imo'},
  {name: 'Jigawa', id: 18, value: 'jigawa'},
  {name: 'Kaduna', id: 19, value: 'kaduna'},
  {name: 'Kano', id: 20, value: 'kano'},
  {name: 'Kastina', id: 21, value: 'kastina'},
  {name: 'Kebbi', id: 22, value: 'kebbi'},
  {name: 'Kogi', id: 23, value: 'kogi'},
  {name: 'Kwara', id: 24, value: 'kwara'},
  {name: 'Nasarawa', id: 26, value: 'nasarawa'},
  {name: 'Niger', id: 27, value: 'niger'},
  {name: 'Ogun', id: 28, value: 'ogun'},
  {name: 'Ondo', id: 29, value: 'ondo'},
  {name: 'Osun', id: 30, value: 'osun'},
  {name: 'Oyo', id: 31, value: 'oyo'},
  {name: 'Plateau', id: 32, value: 'plateau'},
  {name: 'Rivers', id: 33, value: 'rivers'},
  {name: 'Sokoto', id: 34, value: 'sokoto'},
  {name: 'Taraba', id: 35, value: 'taraba'},
  {name: 'Yobe', id: 36, value: 'yobe'},
  {name: 'Zamfara', id: 37, value: 'zamfara'},
];

export default statesList;
