module.exports = {
  LOAD_START: 'auth/LOAD_START',
  LOAD_END: 'auth/LOAD_END',
  SAVE_USER_ROLES: 'auth/SAVE_USER_ROLES',
  SAVE_CATEGORIES: 'auth/SAVE_CATEGORIES',
  SAVE_BUSINESS_TYPES: 'auth/SAVE_BUSINESS_TYPES',
  SAVE_USER_INFO: 'auth/SAVE_USER_INFO',
  RESET_USER_INFO: 'auth/RESET_USER_INFO',
};
