module.exports = {
  LOAD_START: 'delievery/LOAD_START',
  LOAD_END: 'delievery/LOAD_END',
  SAVE_DELIVERY_DATA: 'delievery/SAVE_DELIVERY_DATA',
  SAVE_DELIVERY_SCHEDULE: 'delivery/SAVE_DELIVERY_SCHEDULE',
  CLEAR_DELIVERY_DATA: '/delivery/CLEAR_DELIVERY_DATA',
  IMAGE_LOAD_START: 'IMAGE_LOAD_START',
  IMAGE_LOAD_END: 'IMAGE_LOAD_END',
  SAVE_DELIVERY_LOCATION_INFO: 'delivery/SAVE_DELIVERY_LOCATION_INFO',
  SAVE_DELIVERY_HISTORY: 'delivery/SAVE_DELIVERY_HISTORY',
  TRACK_DELIVERY_HISTORY: 'delivery/TRACK_DELIVERY_HISTORY',
  SAVE_UPLOADED_IMAGE: 'delivery/SAVE_UPLOADED_IMAGE',
};
